version: '3'

services:
  database:
    image: postgres:11.8-alpine
    container_name: "teste-software-demo-2"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=teste-software-demo-2
    command:
      - "postgres"
      - "-c"
      - "effective_cache_size=1024MB"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
